apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  mysql-root-password: ZGFuZwo=

microk8s kubectl apply -f mysql-secret.yaml
microk8s kubectl apply -f mysql-pv-pvc.yaml
microk8s kubectl apply -f mysql-statefulset.yaml
microk8s kubectl apply -f mysql-service.yaml
microk8s kubectl apply -f wordpress-pv-pvc.yaml
microk8s kubectl apply -f wordpress-deployment.yaml